# Compatibility
    compatibility_minecraft_versions = >=26.1
    compatibility_fabricloader_versions = >=0.18.0
    compatibility_midnightlib_versions = >=1.9.2

# Mod dependencies
    modmenu_version = 18.0.0-alpha.8
    fabric_loader_version = 0.18.6
    fabric_api_version = 0.145.3+26.1.1

# Third-party dependencies
    qwen3asr4j_version = 1.0.1
