# Compatibility
    compatibility_minecraft_versions = >=26.1
    compatibility_fabricloader_versions = >=0.18.0
    compatibility_midnightlib_versions = >=1.9.3

# Mod dependencies
    modmenu_version = 18.0.0-beta.1
    fabric_loader_version = 0.19.2
    fabric_api_version = 0.148.2+26.1.2

# Third-party dependencies
    qwen3asr4j_version = 1.0.1
