plugins {
    id 'dev.architectury.loom' version '1.13-SNAPSHOT' apply false
    id 'architectury-plugin' version '3.4-SNAPSHOT'
    id 'com.github.johnrengelman.shadow' version '8.1.1' apply false
}

def downloadWhisperJni() {
    def whisperJar = new File(rootDir, "lib/whisper-jni/whisper-jni-${project.whisper_jni_version}.jar")
    if (!whisperJar.exists()) {
        whisperJar.getParentFile().mkdirs()
        whisperJar.withOutputStream { outputStream ->
            def inputStream = new URL("https://github.com/Jaffe2718/whisper-jni/releases/download/v${project.whisper_jni_version}/whisper-jni-${project.whisper_jni_version}.jar").openStream()
            inputStream.transferTo(outputStream)
            inputStream.close()
        }
    }
}

downloadWhisperJni()

architectury {
    minecraft = project.minecraft_version
}

allprojects {
    group = rootProject.maven_group
    version = rootProject.mod_version
}

subprojects {
    apply plugin: 'dev.architectury.loom'
    apply plugin: 'architectury-plugin'
    apply plugin: 'maven-publish'

    base {
        // Set up a suffixed format for the mod jar names, e.g. `example-fabric`.
        archivesName = "$rootProject.archives_name-$project.name"
    }

    repositories {
        maven {
            url = "https://api.modrinth.com/maven"
        }
    }

    dependencies {
        implementation files("$rootDir/lib/whisper-jni/whisper-jni-${whisper_jni_version}.jar")
        minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"
        // mappings loom.officialMojangMappings()

        mappings loom.layered {
            it.mappings("net.fabricmc:yarn:$rootProject.yarn_mappings:v2")
            it.mappings("dev.architectury:yarn-mappings-patch-neoforge:$rootProject.yarn_mappings_patch_neoforge_version")
        }
    }

    java {
        // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
        // if it is present.
        // If you remove this line, sources will not be generated.
        withSourcesJar()

        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 21
    }
}
