# Done to increase the memory available to Gradle.
    org.gradle.jvmargs = -Xmx2G
    org.gradle.parallel = true

# Mod properties
    mod_version = 2.2.0+patch.1
    maven_group = me.jaffe2718
    archives_name = mcmti
    enabled_platforms = fabric,neoforge

# Minecraft properties
    minecraft_version = 1.21
    yarn_mappings = 1.21+build.1
    yarn_mappings_patch_neoforge_version = 1.21+build.6

# Dependent Mods
    architectury_api_version = 13.0.8
    modmenu_version = 11.0.3
    fabric_loader_version = 0.18.4
    fabric_api_version = 0.102.0+1.21
    neoforge_version = 21.0.167
    midnightlib_version = 1.9.2+1.21.1

# Third-party dependencies
    whisper_jni_version = 1.0.1
