# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G -Dfile.encoding=UTF-8

# Fabric Properties
	# check these on https://modmuss50.me/fabric.html
	minecraft_version = 1.21.4
	yarn_mappings = 1.21.4+build.8
	loader_version = 0.16.10

# Mod Properties
	mod_version = 1.1.14
	maven_group = github.jaffe2718
	archives_base_name = mcmti

# Dependencies
	# check this on https://modmuss50.me/fabric.html
	fabric_version=0.118.0+1.21.4
    midnightlib_version=1.6.9
	modmenu_version = 13.0.2

# Third party Java libraries
    vosk_version = 0.3.45

# Compatibility
    compatibility_mc_versions = >=1.21.4
    compatibility_fabricloader_versions = >=0.16.0
    compatibility_midnightlib_versions = >=1.6.2-fabric <=2.0.0-fabric
