# Done to increase the memory available to Gradle.
    org.gradle.jvmargs = -Xmx2G
    org.gradle.parallel = true

# Mod properties
    mod_version = 2.1.9-rc.5
    maven_group = me.jaffe2718
    archives_name = Microphone-Text-Input
    enabled_platforms = fabric,neoforge

# Minecraft properties
    minecraft_version = 1.21.11

# Modding Dependencies
    architectury_api_version = 19.0.1
    yarn_mappings = 1.21.11+build.4
    fabric_loader_version = 0.18.4
    fabric_api_version = 0.141.1+1.21.11
    neoforge_version = 21.11.0-beta
    yarn_mappings_patch_neoforge_version = 1.21+build.4
    midnightlib_version = 1.9.2+1.21.11

# Third-party dependencies
    whisper_jni_version = 0.5.6

# Publish Configuration
    modrinth_version_type = release
