architectury {
    common rootProject.enabled_platforms.split(',')
}

dependencies {
    implementation "net.fabricmc:fabric-loader:${project(':fabric').fabric_loader_version}"
    implementation "maven.modrinth:midnightlib:${rootProject.midnightlib_version}-fabric"
}

configurations {
    testOutput.extendsFrom(testImplementation)
}
