modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/Jaffe2718/Microphone-Text-Input/issues"
license = "MIT"

[[mods]]
modId = "mcmti"
version = "${version}"
displayName = "Microphone Text Input"
authors = "Jaffe2718"
description = '''
Speech recognition chat message input tool for Minecraft.

Official Whisper Model: https://huggingface.co/ggerganov/whisper.cpp
Unofficial Whisper Model: https://huggingface.co/Jaffe2718/ggml-whisper-unofficial
Custom Lib: https://github.com/Jaffe2718/whisper-jni/releases/tag/v1.0.1
VAD: https://huggingface.co/ggml-org/whisper-vad
'''
logoFile = "assets/mcmti/icon.png"
modUrl = "https://modrinth.com/mod/mcmti"

[[dependencies.mcmti]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_versionRange}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.mcmti]]
modId = "minecraft"
type = "required"
versionRange = "${mc_versionRange}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.mcmti]]
modId = "midnightlib"
mandatory = true
versionRange = "[1.0,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.mcmti]]
modId = "architectury"
mandatory = true
versionRange = "${architectury_versionRange}"
ordering = "AFTER"
side = "CLIENT"