plugins {
    id 'com.modrinth.minotaur'
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

repositories {
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
}

sourceSets {
    test {
        compileClasspath += main.compileClasspath
        runtimeClasspath += main.runtimeClasspath
        java {
            srcDirs.addAll(sourceSets.main.java.srcDirs)
        }
        resources {
            srcDirs.addAll(sourceSets.main.resources.srcDirs)
        }
    }
}

loom {
    runs {
        testClient {
            client()
            configName = "Test Minecraft Client"
            mods {
                create(rootProject.archives_name) {
                    sourceSet sourceSets.main
                }
                create('vosk_neoforge') {
                    sourceSet sourceSets.test
                }
            }
            source sourceSets.test
        }
    }
    runs.removeIf {
        it.name == "server"
    }
}

dependencies {
    include forgeDependencies("io.github.jaffe2718:whisper-jni:$rootProject.whisper_jni_version")
    neoForge "net.neoforged:neoforge:$project.neoforge_version"
    modImplementation "dev.architectury:architectury-neoforge:$project.architectury_api_version"
    modImplementation "maven.modrinth:midnightlib:${rootProject.midnightlib_version}-neoforge"
    common(project(path: ':common', configuration: 'namedElements')) { transitive false }
    shadowBundle project(path: ':common', configuration: 'transformProductionNeoForge')

    testImplementation "com.alphacephei:vosk:$project.vosk_version"
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/neoforge.mods.toml') {
        expand "version": project.version,
               "neoforge_version_range": project.neoforge_version_range,
               "architectury_version_range": project.architectury_version_range,
               "minecraft_version_range": project.minecraft_version_range
    }
}

tasks.named('runClient') {
    jvmArgs '-Djava.awt.headless=false'
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    inputFile.set shadowJar.archiveFile
    from(rootDir.toPath().toString() + "/LICENSE") {
        rename { "${it}_${rootProject.archives_name}"}
    }
    archiveFileName = "${rootProject.archives_name}-${rootProject.version}+${project.minecraft_version}-${project.name}.jar"
}

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = 'ynA13Vjn'
    versionNumber = rootProject.mod_version + "-neoforge"
    versionType = rootProject.getPublishVersionType()
    uploadFile = remapJar
    loaders = ["neoforge"]
    dependencies {
        required.project 'architectury-api'
        required.project 'midnightlib'
    }
    changelog = rootProject.ext.publish_changelog
}